env:
  browser: true
  es6: true
parser: '@typescript-eslint/parser'
extends:
    - eslint:recommended
    - plugin:@typescript-eslint/recommended
parserOptions:
  ecmaVersion: 2018
  sourceType: module
rules:
  indent:
    - error
    - 3
  linebreak-style:
    - error
    - windows
  quotes:
    - error
    - single
  semi:
    - error
    - never
  sort-imports:
    - warn
    - ignoreCase: true
  '@typescript-eslint/member-delimiter-style':
    - error
    - multiline:
        delimiter: comma
        requireLast: true
      singleline:
        delimiter: comma
        requireLast: false
  '@typescript-eslint/explicit-member-accessibility':
    - error
